setup: git-addons bash script for subtree addon management (revised)
type
  ./git-addons help
in bash for more info.

heavy changes + git-subtree.sh-based subtree detection

Refs https://gitlab.ilscipio.com/scipio-dev/dev/scipioce-dev/issues/553

diff --git a/git-addons b/git-addons
--- a/git-addons
+++ b/git-addons
@@ -2,8 +2,10 @@
 
 # not portable, oh well
 #BASEDIR=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
-BASEDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
-PROJDIR="${BASEDIR}"
+# maybe later
+#BASEDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+#PROJDIR="${BASEDIR}"
+#cd "${PROJDIR}"
 
 print_title() {
   echo "SCIPIO-ERP addons and themes git (subtree) merging script"
@@ -11,23 +13,25 @@ print_title() {
 }
 
 print_usage() {
-  echo "usage: ./git-addons [action] [addon-name] [options]
+  echo "----------
+usage: ./git-addons [action] [addon-name] [options]
 
 actions:
-  help          how this help dialog
-  pull          add or merge (as appropriate) the named addon into working copy
-                using git subtree
-                --all may be specified instead of addon names to update all
-                addons already added to current working copy.
-  remote-reset  force reset the remote for the specified addon(s)
-                --all may be specified instead of addon names to update all
-  list          list currently installed addons
-                --all may be specified to show all recognized addons instead
-    
+  help                how this help dialog
+  pull                add or merge (as appropriate) the named addon into working copy
+                      using git subtree
+                      --all may be specified instead of addon names to update all
+                      addons already added to current working copy.
+  remote-reset        force reset the remote for the specified addon(s)
+                      --all may be specified instead of addon names to update all
+  list                list currently installed addons
+                      --all may be specified to show all recognized addons instead
+
 options:
-  -v            verbose output
-  --all         for use with pull command
-  -n            dry run (git commands not run)
+  -v, --verbose       verbose output
+  -a, --all           for use with pull command
+  -n, --dry-run       dry run (git commands not run)
+  -e, --no-msg-edit   sets GIT_MERGE_AUTOEDIT=no, so no git prompts for merge messages (unless problems)
 
 This script uses the git subtree command to integrate SCIPIO-ERP addons
 into your working copy of ScipioCE/EE (it does NOT work with submodules at this time).
@@ -47,7 +51,7 @@ NOTE: This script handles common merge cases. If you have any issues,
 you may occasionally need to consult and use the git subtree command directly.
 
 Requirements:
-* Bash 4 or higher
+* Bash 4 or higher (for Linux/Mac; for Windows, use Git Bash, Cygwin or other emulation)
 * Git 2.0 or higher (with git subtree command)
 
 Examples:
@@ -61,7 +65,7 @@ Examples:
 
 print_usage_cmd_pull() {
   echo "pull: add or merges the SCIPIO-ERP addon with the given addon-name.
-  
+
 Alternatively, if --all is provided, pulls all existing addons in the working copy.
 
 If its component directory does not exist, it is added using 'git subtree add' command.
@@ -74,9 +78,9 @@ The command internally knows the correct target folder for the SCIPIO-ERP addons
 
 print_usage_cmd_remote_reset() {
   echo "remote-reset: Reset remote for the addon
-  
+
 Supports --all to reset all addon remotes.
-  
+
 May be needed if you have old repository locations, because the pull command
 will not override existing remotes.
 "
@@ -85,17 +89,24 @@ will not override existing remotes.
 print_addon_line() {
   get_addon_info "$2"
   if [ "$1" == "${ADDON_REPOTYPE}" ]; then
-    local INSTSTR=""
-    if is_addon_present "${ADDON_INFO_STR}"; then
-      if is_addon_subtree "${ADDON_INFO_STR}"; then
-        local INSTSTR=" [INSTALLED, subtree]"
-      elif is_addon_submodule "${ADDON_INFO_STR}"; then
-        local INSTSTR=" [PRESENT - WARNING: appears to be a submodule! incompatible with script]"
-      else
-        local INSTSTR=" [PRESENT - WARNING: may not be a subtree; may be incompatible with script]"
-      fi
+    local INSTSTR=$(print_addon_format)
+    echo "${ADDON_NAME} -> ${ADDON_DIR} ${INSTSTR}"
+  fi
+}
+
+print_addon_format() {
+  if is_addon_dir_present; then
+    if is_addon_subtree; then
+      echo "[INSTALLED, subtree]"
+    elif is_addon_subtree_basic; then
+      echo "[PRESENT - WARNING: git log has no record of this being a git subtree! May be incompatible with script! git subtree likely to fail!]"
+    elif is_addon_submodule; then
+      echo "[PRESENT - WARNING: Appears to be a submodule! Incompatible with script!]"
+    elif is_addon_dir_empty; then
+      echo "[PRESENT - WARNING: Empty addon directory! Incompatible with script!]"
+    else
+      echo "[PRESENT - WARNING: Does not appear to be subtree-compatible! Incompatible with script!]"
     fi
-    echo "${ADDON_NAME} -> ${ADDON_DIR}${INSTSTR}"
   fi
 }
 
@@ -149,6 +160,16 @@ print_msg() {
   echo -e "$@"
 }
 
+print_verbose() {
+  if [ "${VERBOSE}" -eq 1 ]; then echo -e "$@"; fi
+}
+
+debug() {
+  # FIXME: this will break functionality, needs to go to log or stderr or something...
+  #print_verbose "$@"
+  true
+}
+
 print_error_req() {
   print_error "$@"
 }
@@ -157,6 +178,12 @@ print_error_usage() {
   print_error "$@"
   echo ""
   print_usage
+}
+
+print_subheader() {
+  echo -e "\n==========================="
+  echo -e "$@"
+  echo -e "==========================="
 }
 
 callgit() {
@@ -218,7 +245,7 @@ check_requirements() {
     return 2
   fi
   if [ -z "${SCIPIO_ADDONS_URL_EE}" ]; then
-    print_warn "The variable SCIPIO_ADDONS_URL_EE is not set. You will only be able to install community addons from Github. \
+    print_msg "NOTE: The variable SCIPIO_ADDONS_URL_EE is not set. You will only be able to install community addons from Github. \
 If you have purchased an addon from the Scipio store, you must input the base address (ssh://.../SCIPIO-ERP/) provided to you \
 into the git-addons-config file.\n"
     if [ -z "${SCIPIO_ADDONS_URL_CE}" ]; then
@@ -227,11 +254,11 @@ into the git-addons-config file.\n"
     fi
   fi
   if [ -z "${SCIPIO_BRANCH}" ]; then
-    determine_branch || return
+    determine_scipio_branch || return
   fi
 }
 
-determine_branch() {
+determine_scipio_branch() {
   local SCPVER=$(grep '^scipio.release.branch=' "framework/base/config/scipiometainfo.properties" | cut -d= -f2)
   if [ "${SCPVER}" == "dev" ]; then
     SCIPIO_BRANCH="master"
@@ -268,7 +295,7 @@ parse_options() {
     print_error_usage "missing action argument"
     return 2
   fi
-  
+
   if [ "${ACTION}" == "help" ] || [ "${ACTION}" == "-h" ] || [ "${ACTION}" == "--help" ]; then
     ACTION=help
     HELP=1
@@ -282,7 +309,7 @@ parse_options() {
     print_error_usage "Unrecognized action: ${ACTION}"
     return 2
   fi
-  
+
   for ARG; do
     if [ "${ARG}" == "-v" ] || [ "${ARG}" == "--verbose" ]; then
       VERBOSE=1
@@ -290,8 +317,14 @@ parse_options() {
       HELP=1
     elif [ "${ARG}" == "-a" ] || [ "${ARG}" == "--all" ]; then
       ALLADDONS=1
+      if [ ! -z "${TARGETADDONS}" ]; then
+        print_error_usage "--all cannot be used at same time as addon-name list."
+        return 2
+      fi
     elif [ "${ARG}" == "-n" ] || [ "${ARG}" == "--dry-run" ]; then
       DRYRUN=1
+    elif [ "${ARG}" == "-e" ] || [ "${ARG}" == "--no-msg-edit" ]; then
+      export GIT_MERGE_AUTOEDIT=no
     elif [[ "${ARG}" == -* ]]; then
       print_error_usage "Unrecognized option: ${ARG}"
       return 2
@@ -361,57 +394,124 @@ check_target_addons() {
 }
 
 get_present_addons() {
-  ADDONS=$(print_present_addons)
+  ADDONS=
+  for ADDON in $(sort_args "${!SCIPIO_ADDON_MAP[@]}"); do
+    get_addon_info "${SCIPIO_ADDON_MAP[${ADDON}]}"
+    if is_addon_dir_present; then
+      ADDONS="${ADDONS} ${ADDON}"
+    fi
+  done
+  ADDONS=$(echo ${ADDONS})
   if [ -z "${ADDONS}" ]; then
     print_msg "No addons detected in working copy; please install some addons before using --all"
     return 2
   fi
   #print_msg "Addons auto-detected in working copy (--all):\n${ADDONS}"
+  return 0
 }
 
-print_present_addons() {
-  local ADDONS=$(sort_args "${!SCIPIO_ADDON_MAP[@]}")
-  local ADDONS_STR=""
-  for ADDON in ${ADDONS}; do
-    if is_addon_present ${SCIPIO_ADDON_MAP[${ADDON}]}; then
-      ADDONS_STR="${ADDONS_STR} ${ADDON}"
+get_valid_addons() {
+  ADDONS=
+  for ADDON in $(sort_args "${!SCIPIO_ADDON_MAP[@]}"); do
+    get_addon_info "${SCIPIO_ADDON_MAP[${ADDON}]}"
+    if is_addon_supported; then
+      ADDONS="${ADDONS} ${ADDON}"
     fi
   done
-  echo -n ${ADDONS_STR}
+  ADDONS=$(echo ${ADDONS})
+  if [ -z "${ADDONS}" ]; then
+    print_msg "No valid addons detected in working copy; please install some addons before using --all"
+    return 2
+  fi
+  #print_msg "Addons auto-detected in working copy (--all):\n${ADDONS}"
+  return 0
 }
 
-is_addon_present() {
-  get_addon_info "$1"
-  if [ ! -z "${ADDON_DIR}" ] && [ -d "${ADDON_DIR}" ]; then
-    true
-  else
-    false
-  fi
+is_addon_dir_present() {
+  [ ! -z "${ADDON_DIR}" ] && [ -d "${ADDON_DIR}" ]
+}
+
+is_addon_dir_empty() {
+  [ ! -z "${ADDON_DIR}" ] && [ -d "${ADDON_DIR}" ] && [ -z "$(ls -A ${ADDON_DIR})" ]
 }
 
 is_addon_subtree() {
-  get_addon_info "$1"
-  # TODO: is_addon_subtree_in_log.
-  if [ ! -z "${ADDON_DIR}" ] && [ -d "${ADDON_DIR}" ] && [ ! -e "${ADDON_DIR}/.git" ]; then
-    true
-  else
-    false
-  fi
+  is_addon_subtree_basic && is_addon_subtree_deep
 }
 
-is_addon_subtree_in_log() {
-  # TODO: very difficult
-  #git log | grep git-subtree-dir | tr -d ' ' | cut -d ":" -f2 | sort | uniq
-  true
+is_addon_subtree_basic() {
+  [ ! -z "${ADDON_DIR}" ] && [ -d "${ADDON_DIR}" ] && [ ! -z "$(ls -A ${ADDON_DIR})" ] && [ ! -e "${ADDON_DIR}/.git" ]
+}
+
+is_addon_subtree_deep() {
+  local latest_squash=$(find_latest_squash "${ADDON_DIR}")
+  [ ! -z "${latest_squash}" ]
+}
+
+# NOTE: function imported from git package 2.17 git-subtree.sh (this is unlikely to ever change much)
+find_latest_squash() {
+    debug "Looking for latest squash ($dir)..."
+    dir="$1"
+    sq=
+    main=
+    sub=
+    git log --grep="^git-subtree-dir: $dir/*\$" \
+        --no-show-signature --pretty=format:'START %H%n%s%n%n%b%nEND%n' HEAD |
+    while read a b junk
+    do
+        debug "$a $b $junk"
+        debug "{{$sq/$main/$sub}}"
+        case "$a" in
+        START)
+            sq="$b"
+            ;;
+        git-subtree-mainline:)
+            main="$b"
+            ;;
+        git-subtree-split:)
+            sub="$(git rev-parse "$b^0")" ||
+            die "could not rev-parse split hash $b from commit $sq"
+            ;;
+        END)
+            if test -n "$sub"
+            then
+                if test -n "$main"
+                then
+                    # a rejoin commit?
+                    # Pretend its sub was a squash.
+                    sq="$sub"
+                fi
+                debug "Squash found: $sq $sub"
+                echo "$sq" "$sub"
+                break
+            fi
+            sq=
+            main=
+            sub=
+            ;;
+        esac
+    done
+}
+
+is_addon_supported() {
+  is_addon_subtree
+}
+
+check_addon_supported() {
+  if ! is_addon_supported; then
+    if is_addon_subtree_basic; then
+      print_warn "Addon ${ADDON_NAME} -> ${ADDON_DIR} has no record of being a subtree in its log; git subtree pull may fail (if it does, you may need to remove the directory, re-run this script, and reapply your changes after)"
+    else
+      local FMTSTR=$(print_addon_format)
+      print_warn "Skipping ${ADDON_NAME} -> ${ADDON_DIR} - does not appear to be a subtree! Cannot be managed using this script unless removed first.\nDetected as: ${FMTSTR}"
+      return 2
+    fi
+  fi
+  return 0
 }
 
 is_addon_submodule() {
-  get_addon_info "$1"
-  if [ ! -z "${ADDON_DIR}" ] && [ -d "${ADDON_DIR}" ] && [ -e "${ADDON_DIR}/.git" ]; then
-    true
-  else
-    false
-  fi
+  [ ! -z "${ADDON_DIR}" ] && [ -d "${ADDON_DIR}" ] && [ -e "${ADDON_DIR}/.git" ]
 }
 
 pull_addons() {
@@ -422,8 +522,8 @@ pull_addons() {
 }
 
 pull_addons_all() {
-  get_present_addons || return
-  print_msg "Target addons: ${ADDONS}"
+  get_valid_addons || return
+  print_msg "Target addons (auto-detected): ${ADDONS}\nNOTE: If any addons appear to not be detected, use list --all command for more details, or specify them explicitly."
   for ADDON in ${ADDONS}; do
     pull_addon "${SCIPIO_ADDON_MAP[${ADDON}]}" || return
   done
@@ -431,70 +531,64 @@ pull_addons_all() {
 
 pull_addon() {
   get_addon_info "$1"
-  ensure_addon_remote "$1" || return
-  
-  if is_addon_present "$1"; then
-    if ! is_addon_subtree "$1"; then
-      print_warn "Addon ${ADDON_NAME} -> ${ADDON_DIR} does not appear to be a subtree! Cannot be pulled using this script; skipping..."
-      return 0
-    fi
-    print_msg "\nRunning 'git subtree pull' for existing subtree addon ${ADDON_NAME} -> ${ADDON_DIR} (branch: ${SCIPIO_BRANCH})..."
-    callgit subtree pull --squash "--prefix=${ADDON_DIR}" "${ADDON_NAME}" "${SCIPIO_BRANCH}" || { echo "Pull failed. Please verify, resolve conflicts and re-run script."; return 1; }
-  else
-    print_msg "\nRunning 'git subtree add' for new subtree addon ${ADDON_NAME} -> ${ADDON_DIR} (branch: ${SCIPIO_BRANCH})..."
-    callgit subtree add --squash "--prefix=${ADDON_DIR}" "${ADDON_NAME}" "${SCIPIO_BRANCH}" || { echo "Add failed. Please verify, resolve conflicts and re-run script."; return 1; }
-  fi
-}
+  print_subheader "${ADDON_NAME}"
+  if is_addon_dir_present; then
+    check_addon_supported || return 0
+    ensure_addon_remote || return
 
-print_addon_repo_url() {
-  get_addon_info "$1"
-  if [ "${ADDON_URLTYPE}" == "std-url" ]; then
-    local REPOURLVAR="SCIPIO_ADDONS_URL_${ADDON_REPOTYPE^^}"
-    local REPOBASEURL=${!REPOURLVAR}
-    if [ ! -z "${REPOBASEURL}" ]; then
-      echo -n "${REPOBASEURL}${ADDON_NAME}.git"
-    fi
+    print_msg "Running 'git subtree pull' for existing subtree addon ${ADDON_NAME} -> ${ADDON_DIR} (branch: ${ADDON_BRANCH})..."
+    callgit subtree pull --squash "--prefix=${ADDON_DIR}" "${ADDON_NAME}" "${ADDON_BRANCH}" || { echo "Pull failed. Please verify, resolve conflicts and re-run script."; return 1; }
   else
-    # here have actual override URL
-    echo -n "${ADDON_URLTYPE}"
+    ensure_addon_remote || return
+
+    print_msg "Running 'git subtree add' for new subtree addon ${ADDON_NAME} -> ${ADDON_DIR} (branch: ${ADDON_BRANCH})..."
+    callgit subtree add --squash "--prefix=${ADDON_DIR}" "${ADDON_NAME}" "${ADDON_BRANCH}" || { echo "Add failed. Please verify, resolve conflicts and re-run script."; return 1; }
   fi
 }
 
 remote_reset_addons() {
-  print_msg "Target addons: $@\n"
+  print_msg "Target addons: $@"
   for ADDON; do
     remote_reset_addon "${SCIPIO_ADDON_MAP[${ADDON}]}" || return
   done
 }
 
 remote_reset_addons_all() {
-  get_present_addons || return
-  print_msg "Target addons: ${ADDONS}\n"
+  get_valid_addons || return
+  print_msg "Target addons (auto-detected): ${ADDONS}\nNOTE: If any addons appear to not be detected, use list --all command for more details, or specify them explicitly."
   for ADDON in ${ADDONS}; do
     remote_reset_addon "${SCIPIO_ADDON_MAP[${ADDON}]}" || return
   done
 }
 
-ensure_addon_remote() {
-  get_addon_info "$1"
-  if git remote | grep -q '^'"${ADDON_NAME}"'$'; then
-    return 0
-  fi
-  remote_reset_addon "$1"
-}
-
 remote_reset_addon() {
   get_addon_info "$1"
-  local ADDON_URL=$(print_addon_repo_url "$1")
-  if git remote | grep -q '^'"${ADDON_NAME}"'$'; then
-    git remote remove "${ADDON_NAME}"
+  print_subheader "${ADDON_NAME}"
+  check_addon_supported || return 0
+  remote_reset_addon_core
+}
+
+ensure_addon_remote() {
+  if is_remote_exists "${ADDON_NAME}"; then
+    return 0
   fi
-  echo "Adding remote for addon ${ADDON_NAME}: ${ADDON_URL}"
+  remote_reset_addon_core
+}
+
+remote_reset_addon_core() {
+  echo "Setting remote for addon ${ADDON_NAME}: ${ADDON_URL}"
   if [ -z "${ADDON_URL}" ]; then
-    print_error "Cannot determine a repository URL for addon. Did you set SCIPIO_ADDONS_URL_EE in git-addons-config?"
+    print_error "Cannot determine a repository URL for addon ${ADDON_NAME}. Did you set SCIPIO_ADDONS_URL_EE in git-addons-config?"
     return 1
   fi
+  if is_remote_exists "${ADDON_NAME}"; then
+    git remote remove "${ADDON_NAME}"
+  fi
   git remote add "${ADDON_NAME}" "${ADDON_URL}" || { print_error "Could not add remote for addon ${ADDON_NAME}"; return 1; }
+}
+
+is_remote_exists() {
+  git remote | grep -q '^'"${1}"'$'
 }
 
 get_addon_info() {
@@ -508,7 +602,24 @@ get_addon_info() {
   ADDON_NAME="${ADDON_INFO[0]}"
   ADDON_DIR="${ADDON_INFO[1]}"
   ADDON_REPOTYPE="${ADDON_INFO[2]}"
-  ADDON_URLTYPE="${ADDON_INFO[3]}"
+  ADDON_URLPART="${ADDON_INFO[3]}"
+  ADDON_URL=""
+  if [[ "${ADDON_URLPART}" == *//* ]]; then # full url
+    ADDON_URL="${ADDON_URLPART}"
+  else # suffix only; prepend base...
+    local REPOURLVAR="SCIPIO_ADDONS_URL_${ADDON_REPOTYPE^^}"
+    local REPOBASEURL=${!REPOURLVAR}
+    if [ ! -z "${REPOBASEURL}" ]; then
+      ADDON_URL="${REPOBASEURL}${ADDON_URLPART}"
+    fi
+  fi
+  if [[ "${ADDON_URL}" != *".git" ]]; then
+    ADDON_URL="${ADDON_URL}.git"
+  fi
+  ADDON_BRANCHPREFIX="${ADDON_INFO[4]}"
+  ADDON_BRANCHPREFIX=${ADDON_BRANCHPREFIX%"/"}
+  ADDON_BRANCH="${ADDON_BRANCHPREFIX}/${SCIPIO_BRANCH}"
+  ADDON_BRANCH=${ADDON_BRANCH#"/"}
 }
 
 source "./git-addons-config" || { print_error_req "git-addons-config script file is missing"; exit 2; }
